### ISSUE TITLE
Recommendation for token storage?

### ISSUE THREAD

**Issue by tshauck** [sunng87/pgwire#121]
Hi -- thanks for writing this library! I was trying to do something a little different than the examples, so was wondering if you might be able to recommend a good path to support storing a token after auth for future use?

I know I can use `AuthSource::get_password` to get the login/password, so my plan was to use that info to make a request to my auth service to get a token. Where I'm stuck after that is where would be a good place to associate the user login with that token, so that subsequent requests can use that token (e.g. in `do_query`). It also looks like I can get login/pass inside `do_query`, but I'd rather not reauth on every query during the session.

**Comment by sunng87** [comment]
I have included a `metadata_mut` method allows you to grab a mutable reference for `ClientInfo`'s metadata map, where you can store data as key-value mapping.

**Comment by tshauck** [comment]
Ok cool, will have a look there, thanks!
