### ISSUE TITLE
Support for sending NOTIFY to a connected client

### ISSUE THREAD

**Issue by mdwaud** [sunng87/pgwire#132]
Hello! 

Do you have plans to support the ability to send a NOTIFY event to a connected client? I'm considering using pgwire for a project where my program receives external notifications and wants to pass those on to clients without having to poll.

**Comment by sunng87** [comment]
You can check this example for sending notice message from query handlers. https://github.com/sunng87/pgwire/blob/master/examples/server.rs#L32

Note that I made an API change for this and it will soon be released in 0.17.

**Comment by sunng87** [comment]
Sorry I missed this feature and it looks interesting. Let me add this to `Message` enum and you should be able to use it.

If you have a suggestion for building high level API for LISTEN/NOTIFY, proposal is welcomed.

**Comment by mdwaud** [comment]
Something like
```
pub struct NotificationResponse {
    pid: i32,
    channel: String,
    payload: String,
}

impl Message for NotificationResponse {
    #[inline]
    fn message_type() -> Option<u8> {
        Some(MESSAGE_TYPE_NOTIFICATION_RESPONSE)
    }

    fn message_length(&self) -> usize {
        4 + 4 + 2 + self.channel.len() + 2 + self.payload.len()
    }

    fn encode_body(&self, buf: &mut BytesMut) -> PgWireResult<()> {
        buf.put_i32(self.pid);
        codec::put_cstring(buf, &self.channel);
        codec::put_cstring(buf, &self.channel);

        Ok(())
    }

    fn decode_body(buf: &mut BytesMut, len: usize) -> PgWireResult<Self> {
        let data = NotificationResponse {
            pid: buf.get_i32(),
            channel: codec::get_cstring(buf)?,
            payload: codec::get_cstring(buf)?,
        };
        Ok(Self::new(data))
    }
}```

**Comment by sunng87** [comment]
I just created a patch for this and it's pretty similar to your version.

By high-level API, it's a handler API like our `SimpleQueryHandler` that designed for writing application with `LISTEN/NOTIFY` feature.

**Comment by mdwaud** [comment]
Something like Elixir's [Registry](https://hexdocs.pm/elixir/1.12.3/Registry.html) would be my first thought, where the key is the channel and you can set/get one or more clients based on the channel or send the notification to the channel, which is then distributed to all of the processes. This would also require unregistering clients when they disconnect.

**Comment by mdwaud** [comment]
FYI I tested this locally from within a `do_query` and received the correct response in `psql`
> Asynchronous notification "channel" with payload "payload" received from server process with PID 10087.

Thanks again for the responsiveness and creating a great project.

**Comment by sunng87** [comment]
It's nice to hear about that. May I know your use-case with pgwire library? If it's not suitable to describe publicly, you can send me email sunng@pm.me .
