### ISSUE TITLE
ClientInfo property not supported.

### ISSUE THREAD

**Issue by KKould** [sunng87/pgwire#160]
I tried to run the [Sqlite in Example](https://github.com/sunng87/pgwire/blob/master/examples/sqlite.rs) and connect using the database gui in IDEA, but it prompted `ClientInfo property not supported`.

How should I make it support this?

![image](https://github.com/sunng87/pgwire/assets/91525956/0e80ebab-2484-4570-8548-bc0b7f3c7f74)

ref: https://github.com/sunng87/pgwire/issues/99

**Comment by sunng87** [comment]
@KKould Thank you for reporting this. I don't have an IDEA so I may need more information from you.

1. Did you seen any panic from the server side?
2. Could you please use wireshark to capture the traffic when you do connection test?

**Comment by KKould** [comment]
> @KKould Thank you for reporting this. I don't have an IDEA so I may need more information from you.
> 
> 1. Did you seen any panic from the server side?
> 2. Could you please use wireshark to capture the traffic when you do connection test?

1. https://github.com/sunng87/pgwire/pull/163
2. I tried using WireShake but it looks like there is no message

Tips: This is my first time using this, maybe I'm using it incorrectly
![image](https://github.com/sunng87/pgwire/assets/91525956/6218eea1-6c9e-4b7e-bbbc-3b1e5e4b2caf)

**Comment by sunng87** [comment]
Thank you! Are you capturing the right net interface? If your server is listening to localhost, you need to capture loopback.

**Comment by KKould** [comment]
Oh, it seems I chose the wrong network card. I exported this file from wireshark.

[sqlite.json](https://github.com/sunng87/pgwire/files/14477742/sqlite.json)

**Comment by sunng87** [comment]
Fixed in #163

**Comment by KKould** [comment]
@sunng87 There were some misunderstandings. After I used this pr to fix them, I just prevented the server from throwing errors, but it still prompted `ClientInfo property not supported`.

**Comment by sunng87** [comment]
Sorry, let me reopen this. I will find time to analyse your captured packets.

**Comment by sunng87** [comment]
From the paccap I saw IDEA sends a query `select version()` via extended subprotocol under the hood. This query is not supported by sqlite so it does not reply a result that IDEA expects.

**Comment by KKould** [comment]
> From the paccap I saw IDEA sends a query `select version()` via extended subprotocol under the hood. This query is not supported by sqlite so it does not reply a result that IDEA expects.

Is there a way for it to support it?

**Comment by sunng87** [comment]
We don't have to support it in sqlite. You can add a layer on top of `statement::query` to process these queries out of sqlite. If you are interested in this feature, a PR is welcomed. Also you may want to do the same thing on duckdb example.
