### ISSUE TITLE
`Authentication::SASLFinal` parsing broken with Postgres 14

### ISSUE THREAD

**Issue by Eugeny** [sunng87/pgwire#208]
If the server sends `SASLFinal` and `Authentication(Ok)` together quickly and they end up `recv`'d together, `decode` will eagerly overconsume the buffer when parsing `SASLFinal` due to how #175 was implemented.

The `decode` for `SASLFinal` should not ignore `full_len` and should use `buf.split_to(full_len - 4)` instead of `buf.split()`

**Comment by sunng87** [comment]
Thank you for reporting @Eugeny . I will be looking into this soon.

**Comment by sunng87** [comment]
@Eugeny this should have been fixed in https://github.com/sunng87/pgwire/commit/3a586b08527359ded4b258e5ef06f352fbbfce96 . Can you verify its behaviour on the latest version 0.25?

**Comment by Eugeny** [comment]
My bad - I can confirm it's fixed in 0.25!
