### ISSUE TITLE
Text encoding of binary data bug

### ISSUE THREAD

**Issue by LjPalle** [sunng87/pgwire#223]
Hey, it seems that the text encoding of the `&[u8]` type is not implemented correctly. Specifically, the `ToSqlText` trait implementation for `&[u8]` is missing the `b"\\x"` prefix. The implementation should be something like:
```rust
    fn to_sql_text(
        &self,
        _ty: &Type,
        out: &mut BytesMut,
    ) -> Result<IsNull, Box<dyn Error + Sync + Send>> {
        out.put_slice(b"\\x"); // this is currently missing
        out.put_slice(hex::encode(self).as_bytes());
        Ok(IsNull::No)
    }
```

**Comment by sunng87** [comment]
@LjPalle Thank you! I will create a fix for this soon.
