### ISSUE TITLE
SCRAM Channel binding support

### ISSUE THREAD

**Issue by sunng87** [sunng87/pgwire#27]
As we have finished very basic version of SCRAM support in #26 , `SCRAM-SHA-256-PLUS` is to be added. The plus mechanism introduces channel binding for additional security and verification.

**Comment by sunng87** [comment]
Implemented in #31

**Comment by Neustradamus** [comment]
@sunng87: Good job!

Linked to:
- https://github.com/scram-sasl/info/issues/1
- https://github.com/sunng87/pgwire/pull/26
- https://github.com/sunng87/pgwire/issues/27
- https://github.com/sunng87/pgwire/pull/31

**Comment by Neustradamus** [comment]
@sunng87: Good job!

Can you add RFC 9266: Channel Bindings for TLS 1.3 support too?
- https://github.com/sunng87/pgwire/issues/126

Linked to:
- https://github.com/scram-sasl/info/issues/1
- https://github.com/sunng87/pgwire/pull/26
- https://github.com/sunng87/pgwire/issues/27
- https://github.com/sunng87/pgwire/pull/31
