### ISSUE TITLE
Date showing as integers not as yyyy-mm-dd

### ISSUE THREAD

**Issue by osawyerr** [sunng87/pgwire#53]
Hi there,

It's more of a question... When returning a date using the encoder, I get the integer value rather than the actual date. I'm putting the epoch integer in. I thought this would be automatically converted to the correct format since the type is known in the FieldInfo, but its not the case.

How do you return values that require formatting, like dates? Do you have to format it _manually_ to yyyy-mm-dd before calling DataRowEncoder::encode_text_format_field()? There are no examples of this.

```
l_shipmode  | l_shipdate 
------------+------------
 RAIL       | 9681
 REG AIR    | 9689

```

**Comment by sunng87** [comment]
hi @osawyerr , at the moment pgwire doesn't cover encoding for data types. `postgres-types` does a good job for binary encoding but there is no library to take care of text encoding. So you will need to format your date/time/timestamp types like postgres does and send formatted text into our `DataRowEncoder`.

Examples for postgres text output:

- date: `2023-02-01`
- time: `22:27:25.042674`
- timestamp `2023-02-01 22:27:25.042674`
- timestamptz `2023-02-01 22:31:49.479895+08`

I think we can add such functionality to pgwire to ser/de various rust type into its text format, like `postgres-types` did for binary.

**Comment by sunng87** [comment]
@osawyerr the master branch now has buildt-in text encoding for `SystemTime` and chrono's `NaiveDate`, `NaiveTime` and `NaiveDateTime`. Feel free to try out the new API and feedback are welcomed

**Comment by osawyerr** [comment]
Ah cool. Will do. Thanks.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sunng87** [comment]
Resolved by introducing `ToSqlText`.
