### ISSUE TITLE
ExtendedQueryHandler question

### ISSUE THREAD

**Issue by osawyerr** [sunng87/pgwire#82]
Hi there. I'm trying to override ``ExtendedQueryHandler::on_execute()`` I'm basing my implementation on something similar to the default implementation. However I don't have access to ``QueryResponse::data_rows`` and ``QueryResponse::row_schema`` because they are ``pub(crate)``. 

Was this intentional? If so, how can we get access to data_rows so we can iterate through it?

```rust
#[derive(Getters)]
#[getset(get = "pub")]
pub struct QueryResponse<'a> {
    pub(crate) row_schema: Arc<Vec<FieldInfo>>,
    pub(crate) data_rows: BoxStream<'a, PgWireResult<DataRow>>,
}
```

**Comment by sunng87** [comment]
hi @osawyerr , there are public getters for these fields, you can access with .row_schema()

**Comment by osawyerr** [comment]
Yes I saw those. But they return & and its not clear how to convert a ``&BoxStream`` to a ``BoxStream`` for the data_rows, for example.  

I tried using ``as_ref()`` but then you cant call ``next()`` on whats returned.

**Comment by sunng87** [comment]
I see. I'm on vocation today and will look into this issue tonight.  Perhaps we can add owned version of getters for both fields.

**Comment by sunng87** [comment]
By the way, I just expose `send_query_response` in `0.13.1` I'm not sure if it's what you need.

**Comment by osawyerr** [comment]
Yes thats working well thanks. You might consider making the other helper methods public as well to make defining a ``ExtendedQueryHandler`` easier - ``send_execution_response``, ``send_describe_response``, etc 

Also I have a question, how can we force the ``ExtendedQueryHandler`` to always be called? I have defined it and added it to ``process_socket`` but the ``SimpleQueryHandler`` is being called. Is there a way to disable this?

Just for some background, the reason I'm doing this is I want to call a method call it ``foo()`` __before__ the ``do_query()`` method is executed (it can't be called in the body of ``do_query()``). Thats why I am writing an ``ExtendedQueryHandler`` so that I can call ``foo()`` in ``on_execute``.

I'm not sure if using an ``ExtendedQueryHandler`` is the best way to achieve this.

**Comment by sunng87** [comment]
> Also I have a question, how can we force the ExtendedQueryHandler to always be called? I have defined it and added it to process_socket but the SimpleQueryHandler is being called when I send a query select * from my_table. Is there a way to disable this?

It depends on what type of subquery the client uses. For example, `psql` always uses `simple` subprotocol and sends query in plain text, thus `SimpleQueryHandler` are used to respond it. Clients like JDBC use `extended` subprotocol by default so `ExtendedQueryHandler` are called. 

I assume you are using `foo()` to setup some resource to support `do_query()`. Is it possible to call `foo()` upon the initialization of `SimpleQueryHandler` and `ExtendedQueryHandler`. Both handlers can be implemented on same object. And they are initialized for each client connection.

**Comment by osawyerr** [comment]
Ah that makes sense. I'm using psql for my tests. 

> I assume you are using foo() to setup some resource to support do_query(). Is it possible to call foo() upon the initialization of SimpleQueryHandler and ExtendedQueryHandler. Both handlers can be implemented on same object. And they are initialized for each client connection.

Yes its setting up a resource required for ``do_query()``. Hmmm, I did consider setting the resource up when ``SimpleQueryHandler`` and ``ExtendedQueryHandler`` are initialised as you mentioned. However, those are initialised each time a client connects for the lifetime of the connection. But the requirement is that the resource needs to be initialised on a per query basis.

**Comment by sunng87** [comment]
OK. Then I think you will need to override `on_query` from `SimpleQueryHandler` and `on_execute` from `ExtendedQueryHandler` for your case.
