### ISSUE TITLE
Ability to specify a custom version for SQL clients

### ISSUE THREAD

**Issue by osawyerr** [sunng87/pgwire#86]
Hi there.

Is there currently a way to specify a custom version thats returned when clients connect? Currently this is what is returned:

```
psql (15.3, server 0.14.0)
WARNING: psql major version 15, server major version 0.14.
         Some psql features might not work.
Time: 15.989 ms
```

**Comment by sunng87** [comment]
You can find an how to set these custom parameters in [sqlite](https://github.com/sunng87/pgwire/blob/master/examples/sqlite.rs#L60) example
